### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by bk111** [Language-Tools/pinyin-jyutping#1]
![broken1](https://user-images.githubusercontent.com/28552217/224260091-5623f079-32a8-4c9b-9a96-9eaca0013af4.png)
`import pinyin_jyutping

items = """
1.在野外要进入草丛时，切记要先<em>打草惊蛇</em>。
2、你最好别<em>打草惊蛇</em>，老板很喜欢peter，而你只是<a href="1204587.html" target="_blank">没没无闻</a>的小人物。还是放聪明点儿，别吭声，等待时机。
3、警方守候多日，就是怕<em>打草惊蛇</em>，让歹徒溜了。
4、连长告诉我们,不要<em>打草惊蛇</em>,要对敌人进行围攻。
5、你<em>打草惊蛇</em>了惊什么蛇？
6、我爬山时一定带根棍子，既可以当柺杖，又可以<em>打草惊蛇</em>。
7、这个计谋的关键在于避免<em>打草惊蛇</em>，等对方松懈后，可一举进攻。
7、造 句 网zaojv.com是一部在线造句词典,其宗旨是让大家更快地造出更优秀的句子.
8、对方似仍未察觉，我们先<a href="7130374.html" target="_blank">按兵不动</a>，免得<em>打草惊蛇</em>。
9、最后他们决定最好不要<em>打草惊蛇</em>并且不再进一步讨论这个问题。
10、他的第二个冲动是不必<em>打草惊蛇</em>。
11、你这样<a href="4878879.html" target="_blank">轻举妄动</a>只会<em>打草惊蛇</em>，给下一步的工作带来困难。
12、大家先<a href="2946459.html" target="_blank">不动声色</a>，免得<em>打草惊蛇</em>，让他跑了。
13、我爬山时一定带根棍子，既可以当拐杖，又可以<em>打草惊蛇</em>。
14、你调动这么多警力，岂不<em>打草惊蛇</em>？歹徒当然早就跑掉了。
15、这个计谋的关键在于避免<em>打草惊蛇</em>，等对方鬆懈后，可一举进攻。
16、记者象是一群狗，但有<em>打草惊蛇</em>，就开端吠个不绝。
17、我是说我不想<em>打草惊蛇</em>zaojv.com。
18、为了不<em>打草惊蛇</em>，他只是<a href="185730.html" target="_blank">旁敲侧击</a>地询问了来人几个问题。
19、侦破工作应谨慎保密，不要<em>打草惊蛇</em>。
20、这是敌人的先头部队，放他们过去，以免<em>打草惊蛇</em>，影响全歼敌人主力的计划。
21、这次行动千万要保密,不能<em>打草惊蛇</em>。
22、消息指她们都比平日"格外小心"，以免<em>打草惊蛇</em>，故媒体也未能得知她们的身份。
23、这件事得<a href="2946459.html" target="_blank">不动声色</a>慢慢跟他磨，否则一<em>打草惊蛇</em>后，很难说服他。
24、警方为了避免<em>打草惊蛇</em>，所以派出便衣警察埋伏在四周。
25、这件事急不得，表面要装镇定，以免<em>打草惊蛇</em>。
26、不要做那种<em>打草惊蛇</em>的蠢事，不动则已，要动就必须使罪犯全部落网。
27、小偷已经进来了，所以最好不要<em>打草惊蛇</em>，免着他发现家里有人。
28、你就打听些这样的小消息，还让我埋伏的死士都给暴光了，<em>打草惊蛇</em>了还想要报酬啊。
29、现在的局势非常紧张，我们要<a href="2946459.html" target="_blank">不动声色</a>的观察敌情，以免<em>打草惊蛇</em>。
30、他们不得不自污其行，对那些奸臣们<a href="3028873.html" target="_blank">虚与委蛇</a>，为的是获得为国尽忠的机会，免得<em>打草惊蛇</em>，四面树敌，以致遭受奸臣们的嫉恨与陷害。
"""

items1 = """25、这件事急不得，表面要装镇定，以免<em>打草惊蛇</em>。
21、这次行动千万要保密,不能<em>打草惊蛇</em>。
22、消息指她们都比平日"格外小心"，以免<em>打草惊蛇</em>，故媒体也未能得知她们的身份。
"""
p = pinyin_jyutping.PinyinJyutping()
aa = p.pinyin(items)[0]
print(aa)
![Uploading Screenshot (85).png…]()
`

**Comment by luc-languagetools** [comment]
hi sorry can you explain more concisely what is the issue ?

**Comment by bk111** [comment]
> hi sorry can you explain more concisely what is the issue ?

there is no output for a long time.

**Comment by luc-languagetools** [comment]
Thanks for reporting this, I can confirm i'm seeing the issue, let me think of a fix.

**Comment by luc-languagetools** [comment]
please install pinyin_jyutping 0.5 and try again. It should work this time. The performance issues was due to the fact it was trying to compute all possible pinyin transliterations. With a large input, it'll now only compute the most likely pinyin.

**Comment by luc-languagetools** [comment]
Note that for pinyin_jyutping 0.7, the interface is changing (by default result is returned as a string), and the performance should be good. Have you been able to try it ?

**Comment by luc-languagetools** [comment]
closing, re-open if necessary
