### ISSUE TITLE
request: please add the output from jieba

### ISSUE THREAD

**Issue by bk111** [Language-Tools/pinyin-jyutping#4]
>>>p_jieba.pinyin('忘拿一些东西了')
'忘 拿 一些 东西 了'

>>>p.pinyin('忘拿一些东西了')
'wàng ná yīxiē dōngxī le'

**Comment by luc-languagetools** [comment]
have you tried the `pinyin_all_solutions` method ? it generates the breakdown:
>>> import pinyin_jyutping
>>> p = pinyin_jyutping.PinyinJyutping()
>>> p.pinyin_all_solutions('忘拿一些东西了')
{'word_list': ['忘', '拿', '一些', '东西', '了'], 'solutions': [['wàng'], ['ná'], ['yīxiē'], ['dōngxī', 'dōngxi'], ['le', 'liǎo', 'liào']]}

**Comment by bk111** [comment]
> have you tried the `pinyin_all_solutions` method ? it generates the breakdown:
> 
> > > > import pinyin_jyutping
> > > > p = pinyin_jyutping.PinyinJyutping()
> > > > p.pinyin_all_solutions('忘拿一些东西了')
> > > > {'word_list': ['忘', '拿', '一些', '东西', '了'], 'solutions': [['wàng'], ['ná'], ['yīxiē'], ['dōngxī', 'dōngxi'], ['le', 'liǎo', 'liào']]}

got it.
